#!/usr/bin/env bash
set -eo pipefail
[[ "$TRACE" ]] && set -x

out() {
  echo "** $@"
}

run_escape_to() {
  exec "$@"
}

get_interface_name() {
  echo $(ip -4 -o addr | grep -v "\bbrd\b" | grep -v "\blo\b" | cut -d' ' -f2 | sed -n '1p')
}

run_dnsmasq() {
  exec dnsmasq "$@"
}

main() {
  case "$1" in
  escto)
    shift; run_escape_to "$@";;
  *)
    run_dnsmasq "$@";;
  esac
}

main "$@"
